### ISSUE TITLE
Recurring Element Symbol Bug

### ISSUE THREAD

**Issue by Chuck8521** [ethanmac9/ChemTools#8]
When entering Cl in any place but the very beginning, the program fails to work. Other two-letter elements appear unaffected.

**Comment by ethanmac9** [comment]
The error is thrown at line 364 `int secondNum = Integer.parseInt(test2); number += secondNum;` That's deep into your witchcraft; godspeed, and if you need garlic or a crucifix let me know! @Chuck8521

**Comment by ethanmac9** [comment]
It seems to affect any multiletter element which has uesd its capital letter in the formula.
For example: SnS works fine
![sns](https://cloud.githubusercontent.com/assets/14004010/19291102/200d7e50-8fe1-11e6-9e1f-eaf50d5b5b5f.PNG)

However, SSn throws the same error as the chlorine 
![ssn](https://cloud.githubusercontent.com/assets/14004010/19291114/35b200b4-8fe1-11e6-951f-9427c510a8eb.PNG)

**Comment by Chuck8521** [comment]
Bug found and squashed. Turned out, when searching for duplicates, if one element was the proper prefix of another, the second element would be deleted, but only partially, and that would make the whole thing crash when it tried to parse the leftover letters into numbers.
